# Este es un flujo de trabajo(workflow) basico para ayudar a inicializar con gh Actions.
name: CI

# Control de en que comento va a correr
on:
  # Dispara el workflow en un evento push o pull request, pero solo para la rama "master"
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  # Permite correr el workflow en la pestaña de gh Actions
  workflow_dispatch:

# un flujo de trabajo esta hecho por una o mas trabajos(jobs) estos pueden correr secuencial o paralelamente.
jobs:
  # This workflow contains a single job called "build"
  # Este flujo de trabajo contiene un solo job llamado "build"
  build:
    # El tipo de runner en el cual  el job corrrerá
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    # Secuencia de tareas las cuales serán ejecutadas por el job, estos pasos fueron inspirados
    # de: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
    steps:
      - uses: actions/checkout@v3
      - name: Corriendo para Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Instalación de dependencias
        run: |
          python -m pip install --upgrade pip
          pip install ruff pytest
          if [ -f requirements_dev.txt ]; then pip install -r requirements_dev.txt; fi
      - name: Revisión de sintaxis
        run: |
          # stop the build if there are Python syntax errors or undefined names
          ruff --format=github --select=E9,F63,F7,F82 --target-version=py37 .
          # default set of ruff rules with GitHub Annotations
          ruff --format=github --target-version=py37 .
      - name: Corriendo pruebas unistarias para NSS
        run: |
          # Mostrando directorio
          pwd
          # Mostrando contenido del directorio actual
          ls -lsha .
          # Corriendo prueba especifica
          pytest nss_test.py -s
