# Este es un flujo de trabajo(workflow) basico para ayudar a inicializar con gh Actions.
name: CI

# Control de en que comento va a correr
on:
  # Dispara el workflow en un evento push o pull request, pero solo para la rama "master"
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  # Permite correr el workflow en la pestaña de gh Actions
  workflow_dispatch:

# un flujo de trabajo esta hecho por una o mas trabajos(jobs) estos pueden correr secuencial o paralelamente.
jobs:
  # This workflow contains a single job called "build"
  # Este flujo de trabajo contiene un solo job llamado "build"
  build:
    # El tipo de runner en el cual  el job corrrerá
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    # Secuencia de tareas las cuales serán ejecutadas por el job, estos pasos fueron inspirados
    # de: https://docs.github.com/es/actions/automating-builds-and-tests/building-and-testing-python
    steps:
      - uses: actions/checkout@v3
      - name: Corriendo para Python ${{ matrix.python-version }} OS ${{ matrix.os }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      # Instalación de dependencias
      - name: Instalación de dependencias
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements_dev.txt ]; then pip install -r requirements_dev.txt; fi
      # Linting
      - name: Revisión de sintaxis
        run: ruff check .
      # Testing
      - name: Corriendo pruebas unistarias para NSS
        run: pytest nss_test.py -s
      - name: Corriendo pruebas unistarias para el CURP
        run: pytest curp_test.py -s
